### PR TITLE
Remove encryption from EcDH class & only return the hashed shared key

### LINKED ISSUE #91: MessageFactory should not be required for EcDH
The MessageFactory introduced @afk11 in this [commit](https://github.com/mdanter/phpecc/commit/7ad58016051443e604402db82f01ec1c7f485c4f) is only needed for the encryption/decryption of information. If the EcDH class is only used for the key exchange and not the encryption part, a MessageFactory has always be passed in.
An other issue with this change is that the PublicKeyInterface for a [PrivateKey exchange](https://github.com/mdanter/phpecc/commit/7ad58016051443e604402db82f01ec1c7f485c4f#diff-edb3a091e01a394bdbdc1afc45991755R106) is option. But the recipientKey is [always required](https://github.com/mdanter/phpecc/blob/983212c0b1c6f573192b8afd98c5a67eddc1ed9c/src/Crypto/EcDH/EcDH.php#L212).

In addtion, the current example in the README.md is outdated:
```php
// ...
$bobDh = $bob->createExchange($alice);
$messageForBob = $bobDh->decrypt('... the encrypted message... too lazy to actually generate the encoded message');
```

IMHO the MessageFactory should be passed in as optional parameter into the EcDH constructor or passed as required parameter into encrypt/encryptFile and decrypt/decryptFile.

The test case [EcDhMultiPartyTest.php](https://github.com/mdanter/phpecc/blob/983212c0b1c6f573192b8afd98c5a67eddc1ed9c/tests/unit/Crypto/EcDhMultiPartyTest.php) is a good example of a MessageFactory initialisation, that is never been used.

### PR DESCRIPTION
**Pull request by afk11**
Fixes #91. The motivation is to reduce dependencies (good since mcrypt is no longer maintained), and also since EcDH is a key exchange, not an encryption protocol. 

I've changed the `EcDH::calculateSharedKey()` so the x value is hashed before being returned. This prevents issues where a key has a few low bits of zero, so simply returning the hash would make the class safer to use. 

What are peoples thoughts on this?

Edit: The only other usage of mcrypt is in the URandomNumberGenerator. It could be worth adopting a random_bytes polyfill to remove it completely?

### CODE REVIEW

**Comment by afk11** [comment]
Anyone up for testing if this causes trouble in downstream applications? `calculateSharedKey` now returns binary instead of the decimal X coordinate. This should make it harder to shoot yourself in the foot, but it also may cause trouble for clients who need to derive the same key. 

I note that some implementations already call for hashing X to yield the key. Ultimately, I want to do this in calculateSharedKey using: 
```php
return hash('sha256', pack("H*", $this->adapter->baseConvert($this->secretKey->getX(), 10, 16)), true);
```

@dol enquired about EcDH recently, and @Minishlink had a use case which involved it also?

**Comment by Minishlink** [comment]
Hi, no problem with the web-push library with this. :) Thanks for the notification!

**Comment by dol** [comment]
Thank you for the mentioning. Looks ok from my side.

**Comment by afk11** [comment]
Closing, as I merged an alternative. I didn't change the key calculation function, so this shouldn't affect anyone unless they used the cipher related methods.

**Pull request closed without merging**
