### PR TITLE
Use container based infrastructure in CI

### PR DESCRIPTION
**Pull request by aztech-dev**
This should speed up the builds.

### CODE REVIEW

**Comment by btcdrak** [comment]
@aztech-dev did you see my comments in #bitcoin-dev? :grinning:

**Comment by aztech-dev** [comment]
Nope

**Comment by aztech-dev** [comment]
If you're talking about IRC, I'm not on there...

**Comment by btcdrak** [comment]
Nothing special, I was just suggesting the same thing there a few hours ago.

**Comment by aztech-dev** [comment]
Ah :) I actually saw the notice while checking out the build results, so I figured might as well do it.

**Comment by btcdrak** [comment]
ACK

**Pull request merged**
