### PR TITLE
release notes for v0.6 and update README with version information

### PR DESCRIPTION
**Pull request by afk11**

### CODE REVIEW

**Comment by kornrunner** [comment]
I'd appreciate getting this release tagged. Thank you!

**Comment by afk11** [comment]
Thanks for the poke, I've done this now. FYI this PR is out of date, I bumped it to v1.0.0 since the API's been pretty stable for a while.

**Comment by kornrunner** [comment]
Thank you! Could you please update the package on [packagist.org](https://packagist.org/packages/mdanter/ecc) as well? It's still not showing new release :|

**Comment by afk11** [comment]
Refreshed that, looks to be autoupdating now :+1:

**Pull request merged**
