### PR TITLE
(3) WIP: X509 certs

### PR DESCRIPTION
**Pull request by afk11**
This is a little bigger than I intended. Still a bit to go. 

Adds Certificate/Csr/CertificateAuthority classes, and some factory methods to EcDomain. 

I have to address certificate extensions. I have a PR for PHPASN1 to add the functionality there where an appreciable start has already been made for this. https://github.com/fgrosse/PHPASN1/pull/54

It serializers also, so adding a CLI command to produce certificates really isn't far away. I had a lot of this in my monster PR #84 - but that's gone beyond easy review at this point! 

https://github.com/afk11/phpecc/compare/ec-params...afk11:x509-cert?expand=1

### CODE REVIEW

**Comment by afk11** [comment]
@btcdrak Thinking it might be best to set up a phpecc/x509 repository as quite a lot is needed for this. I'm developing the code stand-alone for now to maintain separation of concerns.

**Comment by btcdrak** [comment]
Done. https://github.com/phpecc/x509

**Comment by btcdrak** [comment]
Does this get closed now?

**Comment by afk11** [comment]
Yup!

**Pull request closed without merging**
