### PR TITLE
WIP - working towards Message signing/verification

### PR DESCRIPTION
**Pull request by afk11**
See #83

### CODE REVIEW

**Comment by afk11** [comment]
Added a DerSignatureSerializer, and finished adding the `phpecc sign` command. 

Added an EcDomain class, which encapsulates the choice of Curve/Generator/Hash function. This provides easy access to a domain specific signer. 

I started working on Certificate functionality, and we can now produce CSR's for keys generated with the library! 

I'll get to the conflicts soon.

**Comment by CoinsnapIntegration** [comment]
Hello mdanter/phpecc hello@runcpa.com,Thank you for registering with our support.Your account has been setup and you can now login to our client portal . Client portal url : https://helpdesk.coinsnap.euEmail: reply@reply.github.com Please reset your password by using following link https://helpdesk.coinsnap.eu?/client/reset_password/TTxGNVA7J0RLLCMhQi0mLUM4VilDLFYxQS0zLUE4VjhVLFMlRjgzMFg5MzhVLiMwVDgzJFYtNjVGLiY4UwpNOEMsVS42KFctMyFELjMpQzlDYFAsI2BQLCNgUSwzJUItIyFELFY0WSxGJFEtQ0VDOTNgVCwmLFY5QyFFCjEwJylFPCZRWStGPUk9JkFVOEJZQztWVGAKYAo=/IywzQFMKYAo=
 Using client portal you can track your existing tickets, submit new tickets and update your profile.

**Comment by afk11** [comment]
@CoinsnapIntegration what is this?

**Comment by CoinsnapIntegration** [comment]
Hello mdanter/phpecc ,Thank you for registering with our support.Your account has been setup and you can now login to our client portal . Client portal url : https://helpdesk.coinsnap.euEmail: reply@reply.github.com Please reset your password by using following link https://helpdesk.coinsnap.eu?/client/reset_password/TTxGNVA7J0RLLCMhQi0mLUM4VilELEY5QjkzNFY4Qz1BLSYoVCxDKFAtUyxSOTMpRCwjQFQsUyxRLFYwVwpNOTYoUSxWJFI5MzhZLjMpQzlDYFAsI2BQLCNgUSwzJUItQy1BODY0WSxGJFEtQ0VDOTNgVCwmLFY5QyFFCjEwJylFPCZRWStGPUk9JkFVOEJZQztWVGAKYAo=/Iy1TRFQKYAo=U
 sing client portal you can track your existing tickets, submit new tickets and update your profile.

**Comment by afk11** [comment]
Been playing with this some more. I realized then you'd only see PGP signatures passed around as base64 - otherwise DER signatures are mainly for over the wire. 

I did find somewhere this would immediately be useful - producing CSR's and certificates. There are now some experimental classes for producing these. Parsing - support is limited, as aside from our curves, we need to keep OID's for the likes of RSA+sha1, etc. Should we bother with this?

Also, I added EcDomain, which requires a NamedCurve and a known hashing algorithm (ie, we have the OID). 

@aztech-dev I know you had looked into message signing, and that we may also have to add the field bit-size at some point. Any thoughts on the stuff here?

**Pull request closed without merging**
